AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template to deploy a Lambda running the FastAPI framework
  behind an API Gateway

Parameters:
  FastApiRootPath:
    Description: >
      FastAPI root path which must matcht the name of the API Gateway
      Deployment Stage. This will add the extra path prefix (eg. /dev)
      that is not seen by the FastAPI application.
    Type: String
    Default: dev
    AllowedValues:
      - dev

Globals:
  Function:
    Timeout: 60

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref libs
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FastApiGateway
            Path: /{proxy+}
            Method: ANY
      CodeUri: ./
      Handler: lambda_restapi.main.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Description: Lambda running the FastAPI framework
      Policies: # AWS Managed Policies
        - AmazonSSMFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Environment:
        Variables:
          ROOT_PATH: !Sub "/${FastApiRootPath}"
      # AutoPublishAlias: live

  FastApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      OpenApiVersion: '3.0.0'

  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: fastapi-python-lib
      Description: Python dependencies for REST APIs
      ContentUri: ../bin/lambda-layer/.
      CompatibleRuntimes:
          - python3.8

Outputs:
  FastApiFunction:
    Description: "Lambda Function ARN to be mapped with a Deployment Resource in the API GTW Console."
    Value: !GetAtt FastApiFunction.Arn
  FastApiGateway:
    Description: "API Gateway endpoint dev URL for the FastAPI rest framework"
    Value: !Sub "https://${FastApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${FastApiRootPath}/docs/"